### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by gaeVG** [Refemi/refemi_front#1]
- [x] challenge the website as it exists today to make it more organised
- [x] make sure there's no code duplication => list new components that need to be created
- [x] add references by theme

**Comment by Lauraillouz** [comment]
This needs to wait for mapping of existing components in [Ticket#2](https://github.com/Refemi/refemi_front/issues/2)

**Comment by Lauraillouz** [comment]
https://alexkondov.com/tao-of-react/

**Comment by Lauraillouz** [comment]
List References by Theme but I have a rendering issue (see screenshot attached
<img width="786" alt="Capture d’écran 2021-12-27 à 17 27 16" src="https://user-images.githubusercontent.com/73298340/147490192-7233b3bd-7e83-4867-8c3d-1af3fb31ac7c.png">
)
It loads twice, but 9/10 times it doesn't render anything.
I'll get back on it later tonight, but if on of you @gaeVG or @mridha-emran have an idea :)
(everything is pushed on branch 01-refactoring)
