### ISSUE TITLE
[Design / bug] Countries list in suggestion reference form goes under content field

### ISSUE THREAD

**Issue by Lauraillouz** [Refemi/refemi_front#107]
On a widescreen, when you click on the list of countries, it goes down to the content field and the prefield text in that field goes over the countries list.
![Capture d’écran 2022-04-11 à 19 58 19 (2)](https://user-images.githubusercontent.com/73298340/162801275-c0eecf87-c51f-4a93-96d7-5514508607f7.png)

Should just be a z-index to add

**Comment by gaeVG** [comment]
It was a wrongly positioned z-index, the property has been added to the component

**Comment by Lauraillouz** [comment]
I can't see the PR anymore?
