### ISSUE TITLE
[BUG] Issues with matching title when reference exists

### ISSUE THREAD

**Issue by Lauraillouz** [Refemi/refemi_front#109]
Referring to 5. in https://github.com/Refemi/refemi_front/issues/88:
When you write a title that matches an existing reference but does not match the punctuation, it doesn't suggest it.
I think we should make the comparaison without punctuation.
Moreover, passed a certain number of characters the matching test does not work anymore
![Capture d’écran 2022-04-11 à 20 06 26 2](https://user-images.githubusercontent.com/73298340/162802225-d2821c1b-78b5-46bd-b6ce-50e88c2cadb4.png)

**Comment by gaeVG** [comment]
I open a PR about a [issue](https://github.com/Refemi/refemi_api/issues/49) I just created on the API to solve the problem you report.
I did some tests, especially with the research you left in the image, and it works normally now

I will also send the PR of the branch I just created to correct the index of the country selection

**Comment by Lauraillouz** [comment]
> I open a PR about a [issue](https://github.com/Refemi/refemi_api/issues/49) I just created on the API to solve the problem you report. I did some tests, especially with the research you left in the image, and it works normally now
> 
> I will also send the PR of the branch I just created to correct the index of the country selection

Backend PR validated. I'm at work and don't have access to DB so, I'm unable to properly test it. The code looked good though.
Could you test different scenarios (title with space, with special character, with accent, with misspelling, very long, very short (when does the search start?), etc).
Also please comment on the criteria that the search uses. If you notice some stuff that could be improved, we can add a TODO for later!

**Comment by gaeVG** [comment]
To answer your comment @Laura, the selection of the search is rather simple, namely which search occurrence `LIKE %search%' previously transformed with the `lower` function.

I did as many searches as possible based on existing reference names, and the presence of special characters is not a problem to get a relevant result
