### ISSUE TITLE
[ DESIGN / LOADER ] Dashboard header display when loading

### ISSUE THREAD

**Issue by gaeVG** [Refemi/refemi_front#113]
When the dashboard page loads, there are three elements that appear relatively quickly at the top left of the view. I'm curious to know where this may be coming from and if it's possible to avoid this?

![image](https://user-images.githubusercontent.com/16835349/164007498-6f34845c-e3e7-46b9-ad26-d1a00ca60a86.png)

**Comment by Lauraillouz** [comment]
From what I see it's the footer. Which means the page is empty. I think I have noticed this issue, but isn't the real problem that we're able to go to the dashboard even without being logged in? I was wondering that th other day. I think we have a redirection issue: if the token is dead, it should show you a message saying you've been logged out with the log in page, no?

**Comment by gaeVG** [comment]
I would have said that it was the dashboard header that is not filled.

On the other hand it has nothing to do with what you are talking about, my page eventually appears. I was wondering if it was possible to avoid seeing it like this because it looks a bit ugly

**Comment by Lauraillouz** [comment]
> I would have said that it was the dashboard header that is not filled.
> 
> On the other hand it has nothing to do with what you are talking about, my page eventually appears. I was wondering if it was possible to avoid seeing it like this because it looks a bit ugly

Probably by placing a loader. OR I've been thinking about creating skeletons, could be cool for a v2! In waiting, let's just place the loader we already coded while the data are loading, what do you think?

**Comment by gaeVG** [comment]
Yes like the others finally, rather than displaying the elements with nothing in them, only display the loader.

When you talk about skeletons, do you mean drawing what we see on the screen by erasing the text?

**Comment by Lauraillouz** [comment]
> Yes like the others finally, rather than displaying the elements with nothing in them, only display the loader.
> 
> When you talk about skeletons, do you mean drawing what we see on the screen by erasing the text?

I mean stuff like that: https://www.erwinhofman.com/blog/skeleton-loading-and-perceived-performance-cro/
But not for now though. Just sharing an idea :)

**Comment by Lauraillouz** [comment]
Solution: place the loader

**Comment by gaeVG** [comment]
I changed the location of the `main` tag so that it remains displayed even when no data has been retrieved, I also applied to it the style that the `section` tag had previously (the other views being configured this way, it seemed more logical to me to apply it to the main, we could discuss it again if necessary)

**Comment by Lauraillouz** [comment]
I'm closing this issue as the loader appears correctly.
However @mridha-emran can you double check on your end that this is not happening anymore, please?
