### ISSUE TITLE
Unable to display the site in Internet Explorer

### ISSUE THREAD

**Issue by gaeVG** [Refemi/refemi_front#117]
When I performed the tests on the different browsers, I was not able to display the site which only gives me the following error:

![image](https://user-images.githubusercontent.com/16835349/165090330-9ad6b3f4-3017-40dd-9980-22ffd0771315.png)

**Comment by gaeVG** [comment]
I think that the error comes from the fact that the browser doesn't support new versions of javascript; we should be able to correct this problem with some adaptations once we have implemented webpack.

It is also known that Internet Explorer requires its own conditions and this ticket should be dedicated to add them.

**Comment by Lauraillouz** [comment]
No need to have a compatibility with IE. Let's test with Edge.
