### ISSUE TITLE
[ STUDY ] Check refreshing pages

### ISSUE THREAD

**Issue by Lauraillouz** [Refemi/refemi_front#125]
At the moment certain components do not call API and are not linked to an url page.
Certain pages need to be proper pages so that when we refresh, we stay on it.

- [ ] Investigate the whole website
- [ ] make a list of pages that need a route
- [ ] create corresponding tickets in backend
- [ ] On each ticket, make sure to write down the impact on other roads/views the new route will have

**Comment by mridha-emran** [comment]
we do not need to make any more routes. for adding new References if create a direct link to FormReference components and add the AddReference components to it, then it will stay on the same page when we refresh the page.

**Comment by Lauraillouz** [comment]
That would be a good solution for just refreshing the page, indeed. However, not using routes causes an issue when using the navigator back button. Do you see what I mean? That's why we linked issue #99 to this one.
So we do need to create routes and call them from backend so that the navigator also follows the pages. This way, when we refresh it calls again the route and reload the data + when you use the navigator back button, it actually takes you to the previous route that was called.
