### ISSUE TITLE
Improve subcategories widget in References page

### ISSUE THREAD

**Issue by gaeVG** [Refemi/refemi_front#13]

**Comment by Lauraillouz** [comment]
Let's pimp up this ugly ass widget. See sidebar menus

**Comment by Lauraillouz** [comment]
I've made it very simple, but I think it's ok for V1. If you wanna have a look on branch 19-general-sass @gaeVG

**Comment by Lauraillouz** [comment]
Done minimum design, I'd say okay for now giving the deadline @gaeVG
