### ISSUE TITLE
Dashboard admin

### ISSUE THREAD

**Issue by gaeVG** [Refemi/refemi_front#17]

**Comment by Lauraillouz** [comment]
Admin dashboard has to show working counters:
- [ ] number of contributors
- [ ] number of pending contributions
- [ ] number of contributions validated
- [ ] number of moderators

It also shows a working space:
- [ ]  list of contributors (and see the list of their validated/pending contributions in a dropdown?)
- [ ] list of pending contributions (and see the name of contributor / sorted by contributor)
- [ ] list of validated contributions (sorted by category)

**Comment by Lauraillouz** [comment]
@gaeVG and this one too :)
So maybe just merge the refactoring branch and start on a new one to continue both dashboards?

**Comment by gaeVG** [comment]
The list of users has not been added with this ticket, but should be done with the #10
