### ISSUE TITLE
Implementation of Axios

### ISSUE THREAD

**Issue by gaeVG** [Refemi/refemi_front#18]
Today, requests are managed using fetch and it would probably be necessary to use the Axios module

**Comment by gaeVG** [comment]
Also, think about setting up an environment file because all the requests are in clear text (http://localhost:8000/...) and the day the project goes into production, we will need to change easily between the dev and the prod

**Comment by Lauraillouz** [comment]
@mridha-emran Where are you at in this ticket? :)

**Comment by mridha-emran** [comment]
yes

**Comment by mridha-emran** [comment]
yes. i am working with Axios.
