### ISSUE TITLE
Let's start a documentation!

### ISSUE THREAD

**Issue by gaeVG** [Refemi/refemi_front#2]
- [x] creation of a mapping of existing components to clarify architecture and provide technical templates of website
- [x] Write presentation of project
- [x] list tech stack

**Comment by Lauraillouz** [comment]
@gaeVG First task of the list for you or no?

**Comment by Lauraillouz** [comment]
[Tech Stack.docx](https://github.com/Refemi/refemi_front/files/7762866/Tech.Stack.docx)
to be checked and completed @gaeVG

**Comment by Lauraillouz** [comment]
[Mapping of existing project.docx](https://github.com/Refemi/refemi_front/files/7763109/Mapping.of.existing.project.docx)
to be checked @gaeVG

**Comment by Lauraillouz** [comment]
[Documentation - REFEMI.pdf](https://github.com/Refemi/refemi_front/files/7785390/Documentation.-.REFEMI.pdf)

Draft

**Comment by Lauraillouz** [comment]
First steps of documentation: OK. Next step to be created for Sprint 2
