### ISSUE TITLE
Handle no results (categories + themes)

### ISSUE THREAD

**Issue by Lauraillouz** [Refemi/refemi_front#21]
Show a no result message if no references are found

**Comment by Lauraillouz** [comment]
@gaeVG This has been handled with the 404, no?

**Comment by gaeVG** [comment]
A function has been added to display the corresponding errors, if the sections or themes exist or not, or if no reference exists in the selected section or theme. The component that displays the errors has been reused for both cases (404 and 204), and displays the codes and their message
