### ISSUE TITLE
Verify that reference doesn't already exist before being able to suggest it

### ISSUE THREAD

**Issue by Lauraillouz** [Refemi/refemi_front#22]
At the moment, with the way we can add a reference, it would be the admin's job to double check a reference suggestion.
I think it would be quite horrible to do every time, especially if you have dozens of references pending.

I suggest before the AddReferece form, we add a form to make sure the reference doesn't already exist.
The form would give you a list of references that seem like yours. 
If you happen to realise that it already exists, you can go check it out (which would make sense when we'll have this little button to suggest amendments and corrections)
If you don't see it, you confirm and go to the AddReference form and what you typed in the "checking form" is passed in this one.

The criteria for references suggestions to make sure you're not adding something that already exists could be:
- title: at least half of what you typed corresponds a title that already exists

If you have any remarks, idea, or questions, please comment!

**Comment by gaeVG** [comment]
With a listening on the input, we would also need an API route created to search the title for one or more existing references ?

**Comment by gaeVG** [comment]
I made a suggestion which is not exactly what was proposed; I tried to answer the request without changing the structure too much

**Comment by Lauraillouz** [comment]
@gaeVG There is no PR attached to this ticket. Where can we test it?

**Comment by gaeVG** [comment]
> I made a suggestion which is not exactly what was proposed; I tried to answer the request without changing the structure too much

You can check this directly on branch [22](https://github.com/Refemi/refemi_front/tree/22)

**Comment by gaeVG** [comment]
An error has been added to the display when the API returns an error: notably when adding a reference if there is a conflict with the name of the reference, but could also support when no theme has been assigned to the reference.
The window returns to the error message level when the button to send the reference has been clicked
