### ISSUE TITLE
Dashboard contributor

### ISSUE THREAD

**Issue by gaeVG** [Refemi/refemi_front#4]
The dashboard must show working counters:
- [x] number of pending contributions of the contributor
- [x] number of validated contributions

And a working space:
- [x] list of pending contributions (and possibility to amend contribution form while it is still pending?)
- [x] list of validated contributions (with their categories ?)

**Comment by Lauraillouz** [comment]
@gaeVG just noticed we have a ticket for that here :)

**Comment by gaeVG** [comment]
Issue was made with the #17
