### ISSUE TITLE
Add themes when suggesting a reference

### ISSUE THREAD

**Issue by Lauraillouz** [Refemi/refemi_front#42]
- [x] on contributor dashboard
- [x] on admin dashboard

**Comment by gaeVG** [comment]
See issue [14](https://github.com/Refemi/refemi_api/issues/14) (refemi_api) for the API part

**Comment by Lauraillouz** [comment]
I accidentally pushed it on develop @gaeVG if you wanna have a look.
I only added the possibility to add themes, but there's the bug I've sent you on slack. I'll create a bug ticket for it
