### ISSUE TITLE
[BUG - design] Fix toggle menu

### ISSUE THREAD

**Issue by Lauraillouz** [Refemi/refemi_front#45]
/!\ MOBILE ONLY

The toggle menu is: 
1. ugly
2. works on a double click instead of a simple click (this might just need a preventDefault of some sort)

- [x] verify that lines are not above button and prevent the button from being clicked properly
- [x] fix the click
- [x] find a place to put the toggle button without it being ugly
- [x] when the menu unfolds, it should take the whole width

**Comment by gaeVG** [comment]
The positions and transitions of the button and the menu container have been revised for a more pleasant interface.

![image](https://user-images.githubusercontent.com/16835349/164451602-320639b7-2f0f-4519-a549-c2441fa31076.png)

The different states have been corrected and should no longer be a problem, either on mobile or on a desktop
