### ISSUE TITLE
Set up pagination for references list

### ISSUE THREAD

**Issue by gaeVG** [Refemi/refemi_front#5]
- [x] The list must always appear in a random order
- [x] pagination after 10 references loaded?
- [x] next page show next 10 results

when click on a reference, pop up with beginning of content ?

**Comment by gaeVG** [comment]
I didn't re-create the ticket related to AG Grid, but this one is directly... I don't have the name of the module you were talking about but we could discuss it here

**Comment by Lauraillouz** [comment]
> I didn't re-create the ticket related to AG Grid, but this one is directly... I don't have the name of the module you were talking about but we could discuss it here

React-table with a [quick integration tutorial](https://www.akashmittal.com/react-table-learn-filter-sort-pagination-in-10-minutes/)

**Comment by Lauraillouz** [comment]
see branch 05-pagination
