### ISSUE TITLE
[Functionnal tests] Test on navigators

### ISSUE THREAD

**Issue by Lauraillouz** [Refemi/refemi_front#50]
It would be interesting to do a first overview of how the website currently behave on every browser:
- safari
- opera
- chrome
- firefox
- IE11
- Microsoft Edge

And write here a report of potential bugs, unwanted events. Verify if sass applies correctly everywhere and the events fire properly.
@gaeVG would you be interested in doing this little study?

**Comment by Lauraillouz** [comment]
> I found a bug in the reference form: it is not possible to remove a selected theme on Firefox, the problem does not occur on a Chromium browser

Could you create a bug ticket related to that?

**Comment by gaeVG** [comment]
> > I found a bug in the reference form: it is not possible to remove a selected theme on Firefox, the problem does not occur on a Chromium browser
> 
> Could you create a bug ticket related to that?

I was going to put this comment in the 88, wouldn't that be more relevant? Would you still like a new ticket?

**Comment by Lauraillouz** [comment]
> > > I found a bug in the reference form: it is not possible to remove a selected theme on Firefox, the problem does not occur on a Chromium browser
> > 
> > 
> > Could you create a bug ticket related to that?
> 
> I was going to put this comment in the 88, wouldn't that be more relevant? Would you still like a new ticket?

To me, ticket 88 is just a testing ticket. If a bug is found while testing, it should be subject to the creation of a new bug ticket that we can solve later on, no?

**Comment by gaeVG** [comment]
It is not wrong 😁i'm going to it !

**Comment by gaeVG** [comment]
It is currently impossible to test the application on Internet Explorer, the only result I can get is a blank page and this error :

![image](https://user-images.githubusercontent.com/16835349/164003990-89486f2a-7acb-444c-b66b-1a5d0e8721db.png)

I think the problem could be solved once we set up webpack because the version should not be compatible with the JS interpreter of IE. That said, it's not a top priority to make the site compatible with this particular browser either...

**Comment by gaeVG** [comment]
I checked all the browsers quoted in the descriptions, and apart from the problem detected with IE, everything seems to function properly on the different media.

I think we can close this ticket

**Comment by Lauraillouz** [comment]
After creating a ticket regarding IE (even though webpack may solve the issue, then we'll close the IE ticket, otherwise we'll still have to deal with it and try and have a runnable app even without all the features available), yes you can close this one!
