### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by Lauraillouz** [Refemi/refemi_front#60]
I have noticed several things that bother me:

When we switch from "Créer un compte" to "Se connecter" or vice vers, there are straight away error messages saying that the form isn't filled properly.
This is not good for the user experience.
The error messages should appear... when an error occurs ;) So only when trying to submit the form with unappropriate or non existent data, or when leaving an input with an information that doesn't match regex.

When we try to create an account with an existing email we get the error message: "Une erreur est survenue lors de la création de votre compte. Veuillez réessayer.". I think a different message should appear like "Un compte existe déjà avec cette adresse email".

When I create an account, it leads me to the log in page with automatically the error message "Une erreur est survenue lors de la création de votre compte. Veuillez réessayer.". This needs to be removed (I think it's linked to issue mentionned in 1.)

When an account is created and we redirect to the login page, it would be nice for the user experience to have a message confirming the creation of his account and inviting him to now login.

**Comment by gaeVG** [comment]
Errors during login, user creation have been taken into account: if the information sent at login or if the creation is impossible, an error will appear at the top of the form to inform the user.
