### ISSUE TITLE
Go Sass

### ISSUE THREAD

**Issue by gaeVG** [Refemi/refemi_front#8]

**Comment by Lauraillouz** [comment]
Move from CSS to Sass.
Which means redoing the whole design.

Idea: should we implement Bulma for general classes like display, font sizes, margins, padding, etc? If we do, we would only upload needed css obviously to not overload project.
What do you think @gaeVG?

**Comment by gaeVG** [comment]
> Idea: should we implement Bulma for general classes like display, font sizes, margins, padding, etc?

Why Bulma? A preference or a technical superiority? When I saw this I thought of Tailwind which is obviously very flexible and allows you to use only what you need

**Comment by Lauraillouz** [comment]
> > Idea: should we implement Bulma for general classes like display, font sizes, margins, padding, etc?
> 
> Why Bulma? A preference or a technical superiority? When I saw this I thought of Tailwind which is obviously very flexible and allows you to use only what you need

Because they all work the same? Bulma, Bootstrap, Tailwind: you can download only the classes you need. Tailwind is actually the only I never used so...

**Comment by gaeVG** [comment]
It seems to me that with Tailwind it is possible, and easy, to select only what interests us, I don't know if Bulma is able to do the same thing...

![image](https://user-images.githubusercontent.com/16835349/146557240-40503e24-d803-4483-b869-101bfcafe750.png)

Should we list the advantages and disadvantages of both perhaps?

**Comment by Lauraillouz** [comment]
Yep, can do the same with Bulma: https://bulma.io/documentation/overview/modular/

I think Tailwind would be better if we'd plan to use it for styling, but we're not. Not sure it's worth a debate to only use it for display, margins, etc. 
My idea was to use a framework to access general classes and make sure we don't repeat any css. 
The rest will be stored in sass variables anyway. Or we just do everything in variables.
So if I could avoid learning another css framework when I know how to use 2 and actually don't like them, it would make me happy :)
However, if you think even for that use Tailwind is a better choice, I'll trust you and we'll go for it!

**Comment by gaeVG** [comment]
That's just it, I don't know!I was just talking about Tailwind because I know that he has that use too, but if you say that Bulma will do, then let's go! I just don't want us to make default choices just because we've mastered the subject, but because it's best for the project 🤗

**Comment by Lauraillouz** [comment]
@gaeVG I'm starting to install sass in the project. However, I realised that I'm gonna need to do a little bit of refactoring and change the source of imports, etc. But if I do that before you start the refactoring of components, we're gonna face some annoying merging issues. Can you let me know when your done with your end of the matter so I can handle my part?

**Comment by Lauraillouz** [comment]
Sass has been installed and set up. Good to go for designing
