### ISSUE TITLE
[Web performances] Fix console warnings / errors

### ISSUE THREAD

**Issue by Lauraillouz** [Refemi/refemi_front#80]
- [x] fix warnings (in the code, a lot of unused expressions need to be removed, also verify no hook is called and not used)
- [x] check errors and fix them
- [x] just a special checkbox for process is not defined :)

**Comment by gaeVG** [comment]
The _process is not defined_ bug has been fixed with the update of the `react-scripts` module to 5.0.0.

However I unfortunately pushed the update on the development branch, so the fix is already effective.

**Comment by gaeVG** [comment]
Except for the bugs mentioned in the corresponding tickets, and those related to the server management services on the test client (refemi.cenne.xyz), I don't have any more messages, neither in the web client console, nor in the webpack development console.

I think we can close this ticket unless you have found other messages @Lauraillouz ?
