### ISSUE TITLE
[Functionnal tests] Test of suggesting reference form

### ISSUE THREAD

**Issue by Lauraillouz** [Refemi/refemi_front#88]
Need to try every functionnality of the reference form and make sure everything works properly:

- [x] 1. I click to add a reference => I have a list of sections that I can select
- [x] 2. I selected a section => I have a list of categories depending on the selected section
- [x] 3. I selected a category => I arrive on a form that I can fill in
- [x] 4. The title of this form reminds the selected category
- [ ] 5. The reference title searches for existing reference: if a similar reference exists, it suggests it, if not nothing happens
- [x] 6. I necessarly have to select between 1 and 5 themes to send the suggestion
- [x] 7. When the suggestion is sent, I have a message that confirms that it has been sent
- [x] 8. When I go back to my dashboard I notice that the counter "Pending" has incremented by 1.

**Comment by Lauraillouz** [comment]
Blocked by https://github.com/Refemi/refemi_front/issues/87

**Comment by Lauraillouz** [comment]
Referring to 5. see https://github.com/Refemi/refemi_front/issues/109

**Comment by gaeVG** [comment]
> Referring to 5. see #109 The mentionned ticket has to be solved before moving further in the tests
> 
> @gaeVG could you also have a look please? Maybe I'm missing something?

I proposed a correction I invite you to go check, it works correctly for me

**Comment by gaeVG** [comment]
> > > Referring to 5. see #109 The mentionned ticket has to be solved before moving further in the tests
> > > @gaeVG could you also have a look please? Maybe I'm missing something?
> > 
> > 
> > I proposed a correction I invite you to go check, it works correctly for me
> 
> Where?

Issue [49](https://github.com/Refemi/refemi_api/issues/49) on the API, I was talking about it in ticket [109](https://github.com/Refemi/refemi_front/issues/109)

**Comment by Lauraillouz** [comment]
I'm closing this ticket since we have a ticket for the step to be done. Please see: https://github.com/Refemi/refemi_front/issues/109
