### ISSUE TITLE
[Go live] Application deployment

### ISSUE THREAD

**Issue by Lauraillouz** [Refemi/refemi_front#92]
Describe the necessary steps to be able to go live

**Comment by gaeVG** [comment]
# 1 - The domain
> Whatever our hosting solution, we need a domain name so that the user can connect to the client from the name rather than the IP address of the web host.

OVH is in my opinion the most logical choice to subscribe to a domain like `refemi.com`. They even offer a migration if the name is not available but you own it, a bit like refemi I think.
# 2 - Hosting
> Several choices are available to us in terms of hosting; we can entrust the management of services to a provider, or rent a server and manage the various services ourselves.
## a. Provider
### I ) Database
1. Heroku : we could very well keep the same database until the [offer](https://www.heroku.com/pricing) evolves when we need it.
2. AWS: [Amazon RDS](https://aws.amazon.com/fr/rds/postgresql/) would seem to be the offer to subscribe to, but honestly I can't figure it out; if you prefer, I'll have to do a little training.
3. [OVH](https://www.ovhcloud.com/fr/public-cloud/postgresql/) also offers its service; I've never used it, but I'm used to their interface and I find it rather relevant
### II ) API server
1. Heroku : while we are at it, it is always possible to host the API with the same providers if we want to limit the access time to the DB.
### III ) Web hosting
1. [OVH](https://www.ovhcloud.com/fr/web-hosting/) : I often used their services which are more than correct, especially the support which is really reactive.
2. AWS : same problem as with the database, I am not comfortable with the interface, but I am sure they offer web hosting services
## a. Personal hosting
I know of a debian overlay ([YunoHost](https://yunohost.org/)) that I personally use that would do the job perfectly as all the necessary services and security settings are pre-configured. One could of course set up everything manually.
### VPS
1. [OVH](https://www.ovhcloud.com/fr/vps/)
2. [Contabo](https://contabo.com/en/)
### Dedicated server
I think that the solution with this type of server is much too much for what we intend to do.
# 3 - Deployment
## 1. API
The server must run constantly to provide data requested by the client; the API must therefore be deployed and launched from a server accessible with remote terminal access via SSH or via a web terminal provided by the provider
## 2. Web client
An Apache or NGinx service (or other but I can only think of those two at the moment) runs on a server and is configured to provide the connected user with what files to use for the given address (a domain name or an IP address); the files are conventionally stored in a `www` folder

If we choose a web host, it is possible that we will only be provided with FTP access to the server folders (like OVH); we will have to transfer the new build every time we update the project. But I suppose it should be possible to deploy the web server with tools provided by the provider.

---
### Webpack
If we opt for a VPS, it will be possible, at first, to configure a webpack script to build the project in the `www` folder of the site, to then add unit tests, to make sure to deploy a new build when the `main` branch is updated, etc. 

Again, I suppose some web host offers this kind of solution, but I don't know of any.

**Comment by Lauraillouz** [comment]
Feedback concerning your analysis:
- for the API server/DB it's a good idea to remain with Heroku
- OVH seems a good solution, I've used it too and it seems like a good choice
- in terms of server I don't understand what you meant, but you're way more informed than I am, so I'll trust your advice :)
- webpack could be the subject of another ticket because we'll need it anyway for the web performances

Questions :
- could we keep deploying on your server as a testing environment?
- should we create another ticket for the different steps to deploy on your server so we can add it to the documentation?
- could create the needed tickets to report the different actions to go live?

**Comment by gaeVG** [comment]
Sorry for the twisted explanations but I preferred to detail the steps exhaustively so as not to forget anything. In short I think we need a virtual machine on which we can deploy the API and the web client.

We can of course continue to test the applications from my server: I have just created a user that I will communicate to you when I have configured the rights so that you can connect to it and act on the repository updates.

I will create the different tickets related to the deployment and try to feed their descriptions; I think the only tickets we need are for the webpack setup and the production server setup (configuration + upload)
