### ISSUE TITLE
[Study/Improvement] Back navigation

### ISSUE THREAD

**Issue by Lauraillouz** [Refemi/refemi_front#99]
I forgot to handle the back button. When we leave the website (for example: I click on a backlink that leads me to a podcast) and I use the back button of the navigator, I go to a 404 page instead of the website.

- [ ] find out the diffrent methods to deal with this
- [ ] decide which solution is best
- [ ] pu it into place

**Comment by Lauraillouz** [comment]
Wait for #125

**Comment by mridha-emran** [comment]
I haven't found the problem that you mention.
